name: Emilio Gabbai-Saldate
favicon: null
layout_spectrum: 0
typography_spectrum: 0.92459
title: Fine Art of Emilio Gabbai-Saldate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.2344295212533325
  lightness: 0.7660611015744507
  saturation: 0.1380521443206817
  rhythmicContrast: 0.732995598576963
purpose: []
