name: Emilio Gabbai-Saldate
favicon: null
layout_spectrum: 0
typography_spectrum: 0.92459
title: Fine Art of Emilio Gabbai-Saldate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060405'
    - '#733216'
    - '#ae7524'
    - '#f2b74d'
    - '#fff9a5'
  brandStrength: 0.5
  lightness: 0.7660611015744507
  saturation: 0.0625
  rhythmicContrast: 0.732995598576963
purpose: []
